//STATS TYPES
export const GET_STATS = "GET_STATS";

//mainTable types
export const GET_ACCOUNTS = "GET_CUENTAS";
export const CHANGED_SELECTED_ACCOUNT = "CHANGED_SELECTED_ACCOUNT";
export const SHOW_MENU =
  "SHOW_MENU";
export const GET_CHARACTERIZATION = "GET_CHARACTERIZATION";
export const CHANGE_CHARACTERIZATION = "CHANGE_CHARACTERIZATION";
export const CHANGE_INDEX ="CHANGE_INDEX";


//gestiones

export const GET_GESTIONES= "GET_GESTIONES";
export const ADD_GESTIONES="ADD_GESTIONES";
