//STATS TYPES
export const GET_STATS = "GET_STATS";

//mainTable types
export const GET_ACCOUNTS = "GET_CUENTAS";
export const CHANGED_SELECTED_ACCOUNT = "CHANGED_SELECTED_ACCOUNT";
export const CHANGE_SHOW_ADD_ARRANGEMENT_ACTION =
  "CHANGE_SHOW_ADD_ARRANGEMENT_ACTION";
export const GET_CHARACTERIZATION = "GET_CHARACTERIZATION";
export const CHANGE_CHARACTERIZATION = "CHANGE_CHARACTERIZATION";
